//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceProClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AttendanceProClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原因不明のエラーです。.
        /// </summary>
        internal static string AnUnknownErrorOccurred {
            get {
                return ResourceManager.GetString("AnUnknownErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出社.
        /// </summary>
        internal static string Arrival {
            get {
                return ResourceManager.GetString("Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に「{0}」済みです。.
        /// </summary>
        internal static string AttendAlready {
            get {
                return ResourceManager.GetString("AttendAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「{0}」に失敗しました。.
        /// </summary>
        internal static string AttendanceFailed {
            get {
                return ResourceManager.GetString("AttendanceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「{0}」が完了しました。.
        /// </summary>
        internal static string AttendanceSucceeded {
            get {
                return ResourceManager.GetString("AttendanceSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退社.
        /// </summary>
        internal static string Depart {
            get {
                return ResourceManager.GetString("Depart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お早うございます。「{0}」しますか？.
        /// </summary>
        internal static string DoYouWantToArrival {
            get {
                return ResourceManager.GetString("DoYouWantToArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部下の勤務表の取得に失敗しました。.
        /// </summary>
        internal static string FailedToFetchSubordinateWorkHour {
            get {
                return ResourceManager.GetString("FailedToFetchSubordinateWorkHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月次勤務表の取得に失敗しました。.
        /// </summary>
        internal static string FailedToFetchWorkingTable {
            get {
                return ResourceManager.GetString("FailedToFetchWorkingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アカウント情報の読み込みに失敗しました。.
        /// </summary>
        internal static string FailedToLoadYourAccount {
            get {
                return ResourceManager.GetString("FailedToLoadYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アカウント情報の保存に失敗しました。.
        /// </summary>
        internal static string FailedToSaveYourAccount {
            get {
                return ResourceManager.GetString("FailedToSaveYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 残業時間を取得しました。.
        /// </summary>
        internal static string GotOvertimeHours {
            get {
                return ResourceManager.GetString("GotOvertimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お知らせ.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に起動済みです。.
        /// </summary>
        internal static string ItHasAlreadyLaunched {
            get {
                return ResourceManager.GetString("ItHasAlreadyLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインに失敗しました。.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインに成功しました。.
        /// </summary>
        internal static string LoginSucceeded {
            get {
                return ResourceManager.GetString("LoginSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 読み込み中です。.
        /// </summary>
        internal static string NowLoading {
            get {
                return ResourceManager.GetString("NowLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードの期限が切れています。更新してください。.
        /// </summary>
        internal static string PasswordHasExpired {
            get {
                return ResourceManager.GetString("PasswordHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 累計残業時間は「{0}時間{1}分」です。.
        /// </summary>
        internal static string TotalOverTimeWork {
            get {
                return ResourceManager.GetString("TotalOverTimeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「未入力」の日があります。.
        /// </summary>
        internal static string YouHaveNoInputDay {
            get {
                return ResourceManager.GetString("YouHaveNoInputDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「月次確定」をする必要があります。.
        /// </summary>
        internal static string YouShouldSendMonthlyCommit {
            get {
                return ResourceManager.GetString("YouShouldSendMonthlyCommit", resourceCulture);
            }
        }
    }
}
