//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceProClient.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AttendanceProClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   原因不明のエラーです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnUnknownErrorOccurred {
            get {
                return ResourceManager.GetString("AnUnknownErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出社 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Arrival {
            get {
                return ResourceManager.GetString("Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に「{0}」済みです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AttendAlready {
            get {
                return ResourceManager.GetString("AttendAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AttendanceFailed {
            get {
                return ResourceManager.GetString("AttendanceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AttendanceSucceeded {
            get {
                return ResourceManager.GetString("AttendanceSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   退社 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Depart {
            get {
                return ResourceManager.GetString("Depart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お早うございます。「{0}」しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DoYouWantToArrival {
            get {
                return ResourceManager.GetString("DoYouWantToArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月次勤務表の取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToFetchWorkingTable {
            get {
                return ResourceManager.GetString("FailedToFetchWorkingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウント情報の読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToLoadYourAccount {
            get {
                return ResourceManager.GetString("FailedToLoadYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウント情報の保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToSaveYourAccount {
            get {
                return ResourceManager.GetString("FailedToSaveYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に起動済みです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItHasAlreadyLaunched {
            get {
                return ResourceManager.GetString("ItHasAlreadyLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインに成功しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoginSucceeded {
            get {
                return ResourceManager.GetString("LoginSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードの期限が切れています。更新してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PasswordHasExpired {
            get {
                return ResourceManager.GetString("PasswordHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 累計残業時間は「{0}時間{1}分」です。.
        /// </summary>
        internal static string TotalOverTimeWork {
            get {
                return ResourceManager.GetString("TotalOverTimeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「未入力」の日があります。.
        /// </summary>
        internal static string YouHaveNoInputDay {
            get {
                return ResourceManager.GetString("YouHaveNoInputDay", resourceCulture);
            }
        }
    }
}
